services:
  - type: web
    name: shopee-alert-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    rootDir: frontend
    plan: free

  - type: web
    name: shopee-alert-backend
    env: go
    buildCommand: go build -o app main.go
    startCommand: ./app
    rootDir: backend
    plan: free